import { TopologyDefinition, TopologyType } from '../types';

export const topologies: TopologyDefinition[] = [
  {
    id: 'centralized',
    name: 'Centralized',
    subtitle: 'Leader-Member',
    icon: '✦',
    masDesc: 'Single orchestrator routes all communication',
    socialDesc: 'Wheel/star network',
    color: '#f59e0b',
    hasRoles: true,
    roles: ['Leader', 'Member'],
    edgeType: 'bidirectional',
    autoConnect: false,
    autoEdgeOnRole: true,
    startPoint: 'Leader receives input',
    endPoint: 'Leader summarizes conversation for output',
    needsStartAgent: false,
  },
  {
    id: 'sequential',
    name: 'Sequential',
    subtitle: 'Pipeline',
    icon: '→',
    masDesc: "Output feeds next agent's input",
    socialDesc: 'Chain network',
    color: '#3b82f6',
    hasRoles: false,
    roles: [],
    edgeType: 'unidirectional',
    autoConnect: false,
    autoEdgeOnRole: false,
    startPoint: 'First agent receives input',
    endPoint: 'Last agent produces output',
    needsStartAgent: false,
    noLoops: true,
  },
  // HIDDEN: hierarchical, p2p, mesh topologies
  // {
  //   id: 'hierarchical',
  //   name: 'Hierarchical',
  //   subtitle: 'Tree',
  //   icon: '△',
  //   masDesc: 'Multi-level managers overseeing workers',
  //   socialDesc: 'Y-pattern or tree',
  //   color: '#8b5cf6',
  //   hasRoles: true,
  //   roles: ['Manager', 'Worker'],
  //   edgeType: 'bidirectional',
  //   autoConnect: false,
  //   autoEdgeOnRole: true,
  //   startPoint: 'Manager receives input',
  //   endPoint: 'Manager summarizes conversation for output',
  //   needsStartAgent: false,
  // },
  // {
  //   id: 'p2p',
  //   name: 'Peer-to-Peer',
  //   subtitle: 'P2P',
  //   icon: '○',
  //   masDesc: 'Agents communicate directly without coordinator',
  //   socialDesc: 'Circle or all-channel',
  //   color: '#22c55e',
  //   hasRoles: false,
  //   roles: [],
  //   edgeType: 'bidirectional',
  //   autoConnect: false,
  //   autoEdgeOnRole: false,
  //   startPoint: 'Specify start agent before run',
  //   endPoint: 'Last agent summarizes for output',
  //   needsStartAgent: true,
  // },
  // {
  //   id: 'mesh',
  //   name: 'Mesh',
  //   subtitle: 'Fully-Connected',
  //   icon: '◈',
  //   masDesc: 'Every agent can reach every other',
  //   socialDesc: 'All-channel (comcon)',
  //   color: '#ec4899',
  //   hasRoles: false,
  //   roles: [],
  //   edgeType: 'bidirectional',
  //   autoConnect: true,
  //   autoEdgeOnRole: false,
  //   startPoint: 'Specify start agent before run',
  //   endPoint: 'Last agent summarizes for output',
  //   needsStartAgent: true,
  // },
  {
    id: 'cyclic',
    name: 'Cyclic',
    subtitle: 'Loop',
    icon: '↺',
    masDesc: 'Allows iterative refinement loops',
    socialDesc: 'Novel pattern',
    color: '#f97316',
    hasRoles: false,
    roles: [],
    edgeType: 'unidirectional',
    autoConnect: false,
    autoEdgeOnRole: false,
    startPoint: 'Specify start agent before run',
    endPoint: 'Last agent summarizes for output',
    needsStartAgent: true,
  },
];

export const getTopologyDefinition = (type: TopologyType): TopologyDefinition | undefined => {
  return topologies.find(t => t.id === type);
};
